#!/bin/sh
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="dcm4chee"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

case "$1" in
    configure)
        # Set the default settings of the service package to those expected by
        # OpenMediaVault.
        if [ -z "${2}" ]; then
            deb-systemd-helper disable "${SERVICE_XPATH_NAME}" >/dev/null || true
            deb-systemd-invoke stop "${SERVICE_XPATH_NAME}" >/dev/null || true
        fi        


        # Update the configuration.
        if ! omv_config_exists "${SERVICE_XPATH}"; then
            echo "Updating configuration"

            omv_config_add_node "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_key "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_key "${SERVICE_XPATH}" "port" "8080"
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
        
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

if [ "$(omv_config_get "${SERVICE_XPATH}/enable")" != "1" ]; then

    if [ -x /etc/init.d/dcm4chee ]; then
        deb-systemd-invoke stop ${SERVICE_XPATH_NAME} >/dev/null || true
    fi
fi

exit 0
