#!/bin/bash -e

# ways we can be called
# http://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
#
# postrm remove
# postrm purge
# old-postrm upgrade new-version
# new-postrm failed-upgrade old-version
# new-postrm abort-install
# new-postrm abort-install old-version
# new-postrm abort-upgrade old-version
# disappearer's-postrm disappear overwriter overwriter-version

DATADIR="/var/lib/dcm4chee"
MYSQLDB="pacsdb"
SECURITY_INFO="--defaults-file=/etc/mysql/debian.cnf"

purge_db() {
    if [ -d /var/lib/mysql/${MYSQLDB} ]; then   
       if [ hash mysql 2>/dev/null ]; then
            echo "Cannot access to mysql to drop database"
        else
            echo "Drop ${MYSQLDB}"
            mysql $SECURITY_INFO --execute "drop database ${MYSQLDB};"     
        fi
    else
        echo "DB ${MYSQLDB} not found!"
    fi
}

case "$1" in

    purge)

        if [ -f "/var/run/dcm4chee/dcm4chee.pid" ]; then
            PID=`cat /var/run/dcm4chee/dcm4chee.pid`;
            if ! kill -0 $PID > /dev/null 2>&1; then
                echo "Removing stale pid file"
                rm /var/run/dcm4chee/dcm4chee.pid
            else
                kill -9 $PID;
            fi
        fi

        if [ -d "/var/run/dcm4chee}" ]; then
            rm -rf "/var/run/dcm4chee"
        fi

        purge_db

        # Make sure all the files are removed
        if [ -d "${DATADIR}" ]; then
            rm -rf "${DATADIR}"
        fi

        # Remove dcm4chee user
        if getent passwd dcm4chee >/dev/null 2>&1; then
            userdel dcm4chee
        fi

        # Remove symbolic link ‘/usr/lib/jvm/java-7-openjdk’
        jvm=/usr/lib/jvm/dcm4chee-openjdk
        if [ -d ${jvm} ]; then
            rm -f ${jvm}
        fi

        if [ -f /etc/init.d/dcm4chee ]; then
            # Remove dcm4che at boot
            update-rc.d -f dcm4chee remove
        fi

        echo "Package dcm4chee-mysql purged!"
    ;;

    remove)
		echo "Package dcm4chee-mysql removed!"
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument" >&2
        exit 1
    ;;

esac

exit 0

