#!/bin/bash -e

# ways we can be called
# http://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
#
# postrm remove
# postrm purge
# old-postrm upgrade new-version
# new-postrm failed-upgrade old-version
# new-postrm abort-install
# new-postrm abort-install old-version
# new-postrm abort-upgrade old-version
# disappearer's-postrm disappear overwriter overwriter-version

DATADIR="/var/lib/dcm4chee"
PSQLDB="pacsdb"
PGUSER="postgres"
CP="pacs"


case "$1" in

    purge)

	sudo -u ${PGUSER} psql -tc "SELECT 1 FROM pg_database WHERE datname = '${PSQLDB}'" | grep -q 1 && { sudo -u ${PGUSER} psql -c "DROP DATABASE ${PSQLDB};"; sudo -u ${PGUSER} psql -c "DROP USER ${CP};"; }
        # Make sure all the files are removed
        if [ -d "${DATADIR}" ]; then
            rm -rf "${DATADIR}"
        fi

        # Remove dcm4chee user
        if getent passwd dcm4chee >/dev/null 2>&1; then
            userdel dcm4chee
        fi

        # Remove symbolic link
        rm -f "/usr/lib/jvm/dcm4chee-openjdk"


        # Remove dcm4che at boot
        update-rc.d -f dcm4chee remove

        echo "Package dcm4chee-psql purged!"
    ;;

    remove)
		echo "Package dcm4chee-psql removed!"
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument" >&2
        exit 1
    ;;

esac

exit 0

