#!/bin/bash -e

SNAME="postgresql"
PSQLDB="pacsdb"
PGUSER="postgres"
DCM4CHEE_DIR="/var/lib/dcm4chee"
CP="pacs"

case "$1" in

    configure)

		# Set prermission to dcm4chee user
		if [ ! -d "${DCM4CHEE_DIR}" ]; then
        	 	mkdir -p "${DCM4CHEE_DIR}"
    		fi
		chown -R dcm4chee:dcm4chee ${DCM4CHEE_DIR}

		# Start postgres
		systemctl enable postgresql
		systemctl is-active --quiet ${SNAME} || service ${SNAME} restart

		sudo -u ${PGUSER} psql -tc "SELECT 1 FROM pg_database WHERE datname = '${PSQLDB}'" | grep -q 1 || { sudo -u ${PGUSER} psql -c "CREATE DATABASE ${PSQLDB};"; sudo -u ${PGUSER} psql -c "CREATE USER ${CP} WITH PASSWORD '${CP}';"; sudo -u ${PGUSER} psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${CP}; GRANT ALL PRIVILEGES ON DATABASE ${PSQLDB} TO ${CP}; ALTER USER ${CP} WITH SUPERUSER;" ; sudo -u ${PGUSER} psql ${PSQLDB} -f ${DCM4CHEE_DIR}/sql/create.psql ; }

		if [ -f /etc/init.d/dcm4chee ]; then
			# Start dcm4che at boot
			update-rc.d -f dcm4chee defaults
		fi

		# Change the native imageio library for the 32-bit x86 processor
		arch=`uname -m`
		[ "$arch" != "x86_64" ] && cp  ${DCM4CHEE_DIR}/tempinst/libclib_jiio.so ${DCM4CHEE_DIR}/bin/native/
		rm -rf ${DCM4CHEE_DIR}/tempinst


		# Create symbolic link ‘/usr/lib/jvm/java-7-openjdk’
		jvm="/usr/lib/jvm/dcm4chee-openjdk"
		openjdk="/var/lib/java-7-oracle"
		mkdir --parents "/usr/lib/jvm"
		echo "Create a symbolic link ${jvm} to ${openjdk}" 
		ln -sfn "${openjdk}" "${jvm}"

		echo "dcm4chee-psql installation completed!"

    	;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;

esac

exit 0
