#!/bin/sh
#
# Copyright (C) 2015 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE="dcm4chee"
SERVICE_XPATH="//services/${SERVICE}"

NAME_DCM4CHEE="dcm4chee-mysql_2.18.2-rc1_all.deb"
NAME_WEASIS="dcm4chee-weasis_2.0.5_all.deb"
LINK_DCM4CHEE="https://github.com/nroduit/openmediavault-dcm4chee/releases/download/v0.9.5/${NAME_DCM4CHEE}"
LINK_WEASIS="https://github.com/nroduit/openmediavault-dcm4chee/releases/download/v0.9.5/${NAME_WEASIS}"
PKG_DCM4CHEE="/var/tmp/${NAME_DCM4CHEE}"
PKG_WEASIS="/var/tmp/${NAME_WEASIS}"
INSTALL_DIR="/var/lib/${SERVICE}"

install()
{ 
    mkdir -p "var/tmp"

    if [ ! -f "${PKG_DCM4CHEE}" ]; then
        echo "Downloading dcm4chee package..."
        wget ${LINK_DCM4CHEE} -O ${PKG_DCM4CHEE} || rm -f ${PKG_DCM4CHEE}
    fi
    

    if [ ! -f "${PKG_WEASIS}" ]; then
        echo "Downloading weasis package..."
        wget ${LINK_WEASIS} -O ${PKG_WEASIS} || rm -f ${PKG_WEASIS}
    fi

    echo "Installing dcm4chee..."
    # Install dcm4chee-mysql and its dependencies
    echo "dpkg -i ${PKG_DCM4CHEE}"
    dpkg -i ${PKG_DCM4CHEE} || apt-get -f install -y
    
    echo "Installing weasis..."
    echo "dpkg -i ${PKG_WEASIS}"
    dpkg -i ${PKG_WEASIS} || apt-get -f install -y
}

remove()
{
    # Remove dcm4chee-mysql and its dependencies
    apt-get -f remove dcm4chee-mysql -y || echo "Cannot remove dcm4chee-mysql package correctly!"
}

config()
{
    echo "Configuration of dcm4chee..."
}


case $2 in
    install)
        install
    ;;

    remove)
        remove
    ;;

    update)
        install
    ;;

    config)
        config
    ;;

    *)
    ;;
esac

#if [ "$(omv_config_get "${SERVICE_XPATH}/enable")" != "0" ]; then
#    invoke-rc.d ${SERVICE} start
#fi

exit 0
