#!/bin/sh
#
# Copyright (C) 2013-2018 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE="dcm4chee"
SERVICE_XPATH="/config/services/${SERVICE}"

NAME_DCM4CHEE="dcm4chee-psql_2.18.3_amd64.deb"
LINK_DCM4CHEE="https://github.com/nroduit/openmediavault-dcm4chee/releases/download/v4.0.1/${NAME_DCM4CHEE}"
PKG_DCM4CHEE="/var/tmp/${NAME_DCM4CHEE}"
INSTALL_DIR="/var/lib/${SERVICE}"

stop()
{
    service dcm4chee stop
}

start()
{
    service dcm4chee start
}

restart()
{
    service dcm4chee restart
}

installdependencies()
{ 
    mkdir -p "var/tmp"

    if [ ! -f "${PKG_DCM4CHEE}" ]; then
        echo "Downloading dcm4chee package..."
        wget ${LINK_DCM4CHEE} -O ${PKG_DCM4CHEE} || rm -f ${PKG_DCM4CHEE}
    fi

    echo "Installing dcm4chee..."
    # Install dcm4chee-psql and its dependencies
    echo "dpkg -i ${PKG_DCM4CHEE}"
    dpkg -i ${PKG_DCM4CHEE} || apt-get -f install -y
    
    if [ "$(omv_config_get "${SERVICE_XPATH}/enable")" != "0" ]; then
        restart
    fi
}

remove()
{

    service dcm4chee stop

    # Remove dcm4chee-psql and its dependencies
    apt-get -f remove dcm4chee-psql -y || echo "Cannot remove dcm4chee-psql package correctly!"
}

config()
{
    echo "Configuration of dcm4chee..."
}



case $1 in
    install)
        installdependencies
    ;;

    remove)
        remove
    ;;

    update)
        installdependencies
    ;;

    config)
        config
    ;;

    start)
        start
    ;;

    restart)
        restart
    ;;

    stop)
        stop
    ;;

    *)
        echo "Unknown command..."
    ;;
esac


exit 0
